[package]
name = "axiom-web"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axiom-config = { path = "../axiom-config" }
axiom-core = { path = "../axiom-core" }
axiom-net = { path = "../axiom-net" }
axum.workspace = true
serde.workspace = true
sha2.workspace = true
tracing.workspace = true
