[package]
name = "axiom-net"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axiom-config = { path = "../axiom-config" }
axiom-core = { path = "../axiom-core" }
axiom-reputation = { path = "../axiom-reputation" }
libc.workspace = true
md-5.workspace = true
sha2.workspace = true
socket2.workspace = true
tokio.workspace = true
tracing.workspace = true
